# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.FileField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='images/img_avatar.png', upload_to='images'),
        ),
    ]
